apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-kubectl
  namespace: {{ .Values.namespace }}
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edit-pods
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: pod-kubectl
roleRef:
  kind: Role
  name: edit-pods
  apiGroup: rbac.authorization.k8s.io
  
  
---
apiVersion: v1
kind: Pod
metadata:
  name: internal-kubectl
  namespace: {{ .Values.namespace }}
spec:
  serviceAccountName: pod-kubectl
  containers:
  - name: internal-kubectl
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    command: ["/bin/sh", "-c", "kubectl -n {{ .Values.namespace }} get pod | grep -e 'nginx-test2' |awk '{print $1}' | while read podname; \
                                do kubectl -n {{ .Values.namespace }} delete pod $podname; sleep 3m; done && \
                                kubectl -n {{ .Values.namespace }} get pod | grep -e 'nginx-test3' |awk '{print $1}' | while read podname; \
                                do kubectl -n {{ .Values.namespace }} delete pod $podname; sleep 3m; done"]
  restartPolicy: Never
