apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-kubectl
  namespace: test

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edit-pods
  namespace: test
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-to-sa
  namespace: test
subjects:
  - kind: ServiceAccount
    name: pod-kubectl
roleRef:
  kind: Role
  name: edit-pods
  apiGroup: rbac.authorization.k8s.io

apiVersion: v1
kind: Pod
metadata:
  name: internal-kubectl
  namespace: test
spec:
  serviceAccountName: pod-kubectl
  containers:
  - name: internal-kubectl
    image: jackmak521/internal-kubectl:latest
    command: ["/bin/sh", "-c", "kubectl -n test get pod | grep -e 'nginx-test2' |awk '{print $1}' | while read podname; \
                                do kubectl -n test delete pod $podname; sleep 10; done && \
                                kubectl -n test get pod | grep -e 'nginx-test3' |awk '{print $1}' | while read podname; \
                                do kubectl -n test delete pod $podname; sleep 10; done"]
  restartPolicy: Never
